include hikari.conf

cursor_shape block
font_family Maple Mono CN Medium
Bold_font auto
font_size 14

remember_window_size no
initial_window_width 168c
initial_window_height 42c
background_opacity 0.8

term xterm-256color

clipboard_control write-clipboard write-primary read-clipboard read-primary


map alt+a send_key ctrl+a
map alt+b send_key ctrl+b
map alt+c send_key ctrl+c
map alt+d send_key ctrl+d
map alt+e send_key ctrl+e
map alt+f send_key ctrl+f
map alt+g send_key ctrl+g
map alt+h send_key ctrl+h
map alt+i send_key ctrl+i
map alt+j send_key ctrl+j
map alt+k send_key ctrl+k
map alt+l send_key ctrl+l
map alt+m send_key ctrl+m
map alt+n send_key ctrl+n
map alt+o send_key ctrl+o
map alt+p send_key ctrl+p
map alt+q send_key ctrl+q
map alt+r send_key ctrl+r
map alt+s send_key ctrl+s
map alt+t send_key ctrl+t
map alt+u send_key ctrl+u
map alt+v send_key ctrl+v
map alt+w send_key ctrl+w
map alt+x send_key ctrl+x
map alt+y send_key ctrl+y
map alt+z send_key ctrl+z

map alt+1 send_text all \e[49;5u
map alt+2 send_text all \e[50;5u
map alt+3 send_text all \e[51;5u
map alt+4 send_text all \e[52;5u
map alt+5 send_text all \e[53;5u
map alt+6 send_text all \e[54;5u
map alt+7 send_text all \e[55;5u
map alt+8 send_text all \e[56;5u
map alt+9 send_text all \e[57;5u

map alt+enter send_text all \x1b\r\n


map ctrl+a send_key alt+a
map ctrl+b send_key alt+b
map ctrl+c copy_to_clipboard
map ctrl+d send_key alt+d
map ctrl+e send_key alt+e
map ctrl+f send_key alt+f
map ctrl+g send_key alt+g
map ctrl+h send_key alt+h
map ctrl+i send_key alt+i
map ctrl+j send_key alt+j
map ctrl+k send_key alt+k
map ctrl+l send_key alt+l
map ctrl+m send_key alt+m
map ctrl+n send_key alt+n
map ctrl+o send_key alt+o
map ctrl+p send_key alt+p
map ctrl+q send_key alt+q
map ctrl+r clear_terminal reset active
map ctrl+s send_key alt+s
map ctrl+t send_key alt+t
map ctrl+u send_key alt+u
map ctrl+v paste_from_clipboard
map ctrl+w send_key alt+w
map ctrl+x send_key alt+x
map ctrl+y send_key alt+y
map ctrl+z send_key alt+z

map ctrl+1 send_key alt+1
map ctrl+2 send_key alt+2
map ctrl+3 send_key alt+3
map ctrl+4 send_key alt+4
map ctrl+5 send_key alt+5
map ctrl+6 send_key alt+6
map ctrl+7 send_key alt+7
map ctrl+8 send_key alt+8
map ctrl+9 send_key alt+9

map ctrl+= change_font_size all +1
map ctrl+- change_font_size all -1


map ctrl+q quit

map kitty_node+t no_op
map kitty_node+q no_op
