- keyboards: ["AT Translated Set 2 keyboard", "Logitech USB Receiver", "Logitech K540/K545"]
  keymap:
    leftalt: leftctrl
    capslock: leftalt
    leftctrl: capslock
    rightalt: rightctrl
    rightctrl: rightalt

  layers:
    - modifiers: ['capslock']
      keymap:
        enter: kpenter
