set -g mode-keys vi
set -g xterm-keys on

set -g history-limit 65536
set -g default-terminal "tmux-256color"

set -g set-titles on
set -g set-titles-string "#H"
set -g base-index 1
set -g renumber-windows on

set -g monitor-activity on
set -g activity-action none
set -g focus-events on

set -g extended-keys on
set -s escape-time 50


set -g @fg "#6f6faf"
set -g @bg "#dddddd"
set -g @sp "#d7d7ff"

set -g status-left ""
set -g status-right "#[fg=#{@bg},bg=#{@fg}]#S"

set -g status-style  fg="#{@fg}",bg="#{@bg}"
set -g mode-style    fg="#{@bg}",bg="#{@fg}"
set -g message-style fg="#{@bg}",bg="#{@fg}",fill="#{@fg}"

set -g window-status-format "#I:#{?window_bell_flag,*,}#W#{?window_bell_flag,*,}"
set -g window-status-current-format "[#W]"

set -g window-status-current-style  fg="#dddddd",bg="#{@fg}"
set -g window-status-activity-style fg="#{@fg}",bg="#{@sp}"
set -g window-status-bell-style     fg="#{@fg}",bg="#{@sp}"


unbind -aq -T prefix
unbind -aq -T copy-mode

set-option -g prefix M-b
bind M-b send M-b

bind M-x send M-x
bind -n M-x command-prompt

bind M-d send M-d
bind -n M-d detach
bind d detach -E 'NO_TMUX=1 exec $SHELL'

bind M-h send M-h
bind M-k send M-k
bind -n M-h split-window -h
bind -n M-k split-window -v

bind M-s send M-s
bind M-w send M-w
bind -n M-s choose-session
bind -n M-w kill-pane

bind M-e send M-e
bind M-p send M-p
bind -n M-e copy-mode
bind -n M-p paste-buffer

bind M-t send M-t
bind M-n send M-n
bind -n M-t new-window -a -c "#{pane_current_path}"
bind -n M-n command-prompt -p "New Session:" "new-session -A -s '%%'"

bind M-1 send M-1
bind M-2 send M-2
bind M-3 send M-3
bind M-4 send M-4
bind M-5 send M-5
bind M-6 send M-6
bind M-7 send M-7
bind M-8 send M-8
bind M-9 send M-9
bind M-0 send M-10
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 0

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection

bind -T copy-mode-vi f send -X search-again
bind -T copy-mode-vi F send -X search-reverse
bind -T copy-mode-vi n send -X next-prompt
bind -T copy-mode-vi e send -X previous-prompt
bind -T copy-mode-vi N send -X halfpage-down
bind -T copy-mode-vi E send -X halfpage-up

set -g set-clipboard on
set -gq get-clipboard both # tmux >= 3.7
set -g allow-passthrough all

set -g mouse on
unbind -n MouseDown3Pane
bind -T copy-mode-vi Space send -X cancel
bind -T copy-mode-vi Escape send -X cancel
bind -T copy-mode-vi BSpace send -X cancel
bind -T copy-mode-vi MouseUp1Pane send -X clear-selection
bind -T copy-mode-vi MouseDown3Pane send -X cancel
bind -T copy-mode-vi DoubleClick1Pane send-keys -X select-word \; run-shell -d 0.3 \; send-keys -X copy-selection-no-clear
bind -T copy-mode-vi TripleClick1Pane send-keys -X select-line \; run-shell -d 0.3 \; send-keys -X copy-selection-no-clear
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-no-clear

# set -g terminal-overrides 'xterm*:smcup@:rmcup@' # scrolling

set-option -g update-environment "DISPLAY SSH_CLIENT SSH_AUTH_SOCK SSH_AGENT_PID"
