set -g mode-keys vi
set -g xterm-keys on

set -g history-limit 65536
set -g default-terminal "tmux-256color"

set -g set-titles on
set -g set-titles-string "#H"
set -g base-index 1
set -g renumber-windows on

set -g status-left ""
set -g status-right "#[fg=#dddddd,bg=#6f6faf]#S"

set -g status-style  fg="#6f6faf",bg="#eeeeee"
set -g mode-style    fg="#dddddd",bg="#6f6faf"
set -g message-style fg="#dddddd",bg="#6f6faf",fill="#6f6faf"

set -g window-status-format "#I:#{?window_bell_flag,*,}#W#{?window_bell_flag,*,}"
set -g window-status-current-format "[#W]"

set -g window-status-current-style  fg="#dddddd",bg="#6f6faf"
set -g window-status-activity-style fg="#6f6faf",bg="#d7d7ff"
set -g window-status-bell-style     fg="#6f6faf",bg="#d7d7ff"

set -g monitor-activity on
set -g activity-action none

set -g escape-time 256
set -g focus-events on

set -g extended-keys on


unbind -aq -T prefix
unbind -aq -T copy-mode

set-option -g prefix M-b
bind M-b send M-b

bind : command-prompt

bind M-d detach
bind d detach -E 'NO_TMUX=1 exec $SHELL'

bind M-h split-window -h
bind M-k split-window -v

bind M-s choose-session
bind M-e copy-mode
bind M-p paste-buffer

bind M-t send M-t
bind -n M-t new-window -c "#{pane_current_path}"
bind M-n send M-n
bind -n M-n command-prompt -p "New Session:" "new-session -A -s '%%'"

bind M-1 send M-1
bind M-2 send M-2
bind M-3 send M-3
bind M-4 send M-4
bind M-5 send M-5
bind M-6 send M-6
bind M-7 send M-7
bind M-8 send M-8
bind M-9 send M-9
bind M-0 send M-10
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 0

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection

bind -T copy-mode-vi f send -X search-again
bind -T copy-mode-vi F send -X search-reverse
bind -T copy-mode-vi n send -X next-prompt
bind -T copy-mode-vi e send -X previous-prompt
bind -T copy-mode-vi N send -X halfpage-down
bind -T copy-mode-vi E send -X halfpage-up

set -g set-clipboard on
set -gq get-clipboard both # tmux >= 3.7
set -g allow-passthrough all

set -g mouse on
set -s escape-time 128
unbind -n MouseDown3Pane
bind -T copy-mode-vi Tab send -X cancel
bind -T copy-mode-vi Escape send -X cancel
bind -T copy-mode-vi MouseUp1Pane send -X cancel
bind -T copy-mode-vi MouseDown3Pane send -X cancel
bind -T copy-mode-vi DoubleClick1Pane select-pane \; send-keys -X select-word \; run-shell -d 0.3 \; send-keys -X copy-selection-no-clear
bind -T copy-mode-vi TripleClick1Pane select-pane \; send-keys -X select-line \; run-shell -d 0.3 \; send-keys -X copy-selection-no-clear
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-no-clear

# set -g terminal-overrides 'xterm*:smcup@:rmcup@' # scrolling

set-option -g update-environment "DISPLAY SSH_CLIENT SSH_AUTH_SOCK SSH_AGENT_PID"
